apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: vsphere-eksa
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "$CONTROL_PLANE_HOSTNAME"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vsphere-eksa-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: vsphere-eksa
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vsphere-eksa-etcd
  kubernetesVersion: "1.30"
  managementCluster:
    name: vsphere-eksa
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vsphere-eksa
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: vsphere-eksa
spec:
  datacenter: "$VSPHERE_DATACENTER"
  insecure: false
  network: "$VSPHERE_NETWORK"
  server: "$VSPHERE_SERVER"
  thumbprint: "$VSPHERE_THUMBPRINT"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vsphere-eksa-cp
spec:
  datastore: "$VSPHERE_DATASTORE"
  diskGiB: 25
  folder: "$VSPHERE_FOLDER"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "$VSPHERE_RESOURCE_POOL"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa $MY_SSH_KEY

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vsphere-eksa
spec:
  datastore: "$VSPHERE_DATASTORE"
  diskGiB: 25
  folder: "$VSPHERE_FOLDER"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "$VSPHERE_RESOURCE_POOL"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa $MY_SSH_KEY

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vsphere-eksa-etcd
spec:
  datastore: "$VSPHERE_DATASTORE"
  diskGiB: 25
  folder: "$VSPHERE_FOLDER"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: "$VSPHERE_RESOURCE_POOL"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa $MY_SSH_KEY

---

